config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: 'dashboards#index'

  resources :users, only: [] do
    resources :physicals, only: [:create, :new, :destroy, :edit, :update, :index]
  end

  namespace :admin do
    resources :users do
      post :lock, on: :member
      post :unlock, on: :member
    end
  end

end

app/models/concerns/grade.rb
module Grade
  extend ActiveSupport::Concern

  ROLE = [['管理者', 100], ['一般', 0]]
  SEX = [['男性', 0], ['女性', 1]]
end

app/models/concerns/graph.rb
# -*- coding: utf-8 -*-
module Graph
  extend ActiveSupport::Concern

  included  do
    def self.hw_graph
      physicals = order(:measurement_date).limit(7)
      LazyHighCharts::HighChart.new('graph') do |f|
        f.title(text: '身長 & 体重')
        f.xAxis(categories: physicals.pluck(:measurement_date))
        f.series(name: '身長(cm)', yAxis: 0, data: physicals.pluck(:height))
        f.series(name: '体重(kg)', yAxis: 1, data: physicals.pluck(:weight))
        f.yAxis [
          { title: { text: '身長(cm)' } },
          { title: { text: '体重(kg)' }, opposite: true }
        ]
        f.legend(align: 'right', verticalAlign: 'top', y: 75, x: -50, layout: 'vertical')
      end
    end

    def self.bpp_graph
      physicals = order(:measurement_date).limit(7)
      LazyHighCharts::HighChart.new('graph') do |f|
        f.title(text: '血圧 & 脈拍')
        f.xAxis(categories: physicals.pluck(:measurement_date))
        f.series(name: '最高血圧', yAxis: 0, data: physicals.pluck(:sbp))
        f.series(name: '最低血圧', yAxis: 0, data: physicals.pluck(:dbp))
        f.series(name: '脈拍', yAxis: 0, data: physicals.pluck(:pulse))
        f.yAxis [
          { title: { text: '血圧 脈拍' } }
        ]
        f.legend(align: 'right', verticalAlign: 'top', y: 75, x: -50, layout: 'vertical')
      end
    end
  end
end

app/models/group.rb
# == Schema Information
#
# Table name: groups
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Group < ActiveRecord::Base
  has_many :group_users
  has_many :users, through: :group_users
end

app/models/group_user.rb
# == Schema Information
#
# Table name: group_users
#
#  id         :integer          not null, primary key
#  group_id   :integer
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class GroupUser < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
end

app/models/physical.rb
# == Schema Information
#
# Table name: physicals
#
#  id               :integer          not null, primary key
#  user_id          :integer          default(0), not null
#  height           :float            default(0.0), not null
#  weight           :float            default(0.0), not null
#  sbp              :integer          default(0), not null
#  dbp              :integer          default(0), not null
#  pulse            :integer          default(0), not null
#  bmi              :float            default(0.0), not null
#  measurement_date :date             not null
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

class Physical < ActiveRecord::Base
  belongs_to :user
  before_save :calc_bmi
  before_update :calc_bmi

  include Graph

  def calc_bmi
    self.bmi = weight / (height / 100.0)**2 if height != 0
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  failed_attempts        :integer          default(0), not null
#  unlock_token           :string
#  locked_at              :datetime
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  name                   :string           default(""), not null
#  account                :string           default(""), not null
#  sex                    :integer
#  birth                  :date
#  role                   :integer          default(0), not null
#

class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :lockable
  attr_accessor :login

  has_many :physicals
  has_many :group_users
  has_many :groups, through: :group_users

  before_save :update_account!

  delegate :hw_graph, to: :physicals
  delegate :bpp_graph, to: :physicals

  validates :email, format: {
    with:    /\A.+@.+\.kagawa-u\.ac\.jp\z/,
    message: 'は大学のもの(kagawa-u.ac.jp)を利用してください。'
  }

  module Role
    GENERAL = 0
    ADMIN = 100
  end

  def admin?
    Role::ADMIN <= role
  end

  def update_account!
    self.account = email.split('@').first
  end

  def update_without_current_password(params, *options)
    params.delete(:current_password)
    params.delete(:password) if params[:password].blank?
    params.delete(:password_confirmation) if params[:password_confirmation].blank?

    clean_up_passwords
    update_attributes(params, *options)
  end

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    login = conditions.delete(:login)
    if login
      find_by('account = :value OR email = :value', value: login)
    else
      find_by(conditions)
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_user!
  before_action :load_user, except: [:index, :new, :create]

  def index
    @search = User.search(params[:q])
    @users = @search.result.page(params[:page]).per(20)
  end

  def edit
    render :show_modal_form
  end

  def update
    @user.update_without_current_password(user_params)
    render :reload
  end

  def new
    render :show_modal_form
  end

  def create
    @user = User.new(user_params)
    @user.save
    render :reload
  end

  def destroy
    @user.destroy
    render :reload
  end

  def lock
    @user.lock_access!
    render :reload
  end

  def unlock
    @user.unlock_access!
    render :reload
  end

  private

  def user_params
    params.require(:user).permit(
      :email, :name, :birth, :password, :role, :sex
    )
  end

  def load_user
    return unless params[:id]
    @user = User.find_by(id: params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def admin_user!
    render file: "#{Rails.root}/public/404.html", layout: false, status: 404 unless current_user.admin?
  end

  protected

  def configure_permitted_parameters
    allows = [:email, :name, :sex, :birth]
    devise_parameter_sanitizer.for(:sign_up) << allows
    devise_parameter_sanitizer.for(:account_update) << allows
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
  end
end

app/controllers/physicals_controller.rb
# -*- coding: utf-8 -*-
class PhysicalsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_user, only: [:index, :create]
  before_action :set_physical, only: [:edit, :update, :destroy]

  def index
    @height_weight = @user.hw_graph
    @bp_pulse = @user.bpp_graph
  end

  def new
    render :show_modal_form
  end

  def create
    @physical = @user.physicals.create(physical_params)
    render :reload
  end

  def edit
    render :show_modal_form
  end

  def update
    @physical.update(physical_params)
    render :reload
  end

  def destroy
    @physical.destroy
    render :reload
  end

  private

  def physical_params
    params[:physical].permit(
      :height, :weight,
      :sbp, :dbp, :pulse,
      :measurement_date
    )
  end

  def set_user
    return unless params[:user_id]
    @user = User.find(params[:user_id])
  end

  def set_physical
    return unless params[:id]
    @physical = Physical.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/users/_form.html.slim
- unless user
  - user = User.new
  - title = 'ユーザの新規作成'
  - submit = '作成'
- else
  - title = 'ユーザの更新'
  - submit = '更新'

.uk-modal-dialog style="padding-bottom: 0"
  a.uk-modal-close.uk-close

  = form_for [:admin, user], html: { class: 'uk-form uk-form-stacked' }, remote: true do |f|
    .uk-modal-header
      h4.bold
        = fa_icon 'user', text: title

    .uk-form-row
      .uk-form-icon
        i.uk-icon-envelope
        = f.text_field :email, autofocus: true, placeholder: 'メールアドレス', style: 'padding-left: 30px;'
      .uk-form-help-block#user-email-error
    .uk-form-row
      .uk-form-icon
        i.uk-icon-font
        = f.text_field :name, placeholder: '名前', style: 'padding-left: 30px;'
      .uk-form-help-block#user-name-error
    .uk-form-row
      = f.select :sex, Grade::SEX, { prompt: true }, { class: 'uk-width-1-1' }
    .uk-form-row
      = f.text_field :birth, placeholder: '誕生日', class: 'uk-width-1-1', "data-uk-datepicker" => "{format: 'YYYY-MM-DD'}", readonly: true
    - if submit == '作成'
      .uk-form-row
        .uk-form-icon
          i.uk-icon-key
          = f.password_field :password, autocomplete: 'off', placeholder: 'パスワード', style: 'padding-left: 30px;'
        .uk-form-help-block#user-password-error
      .uk-form-row
        .uk-form-icon
          i.uk-icon-key
          = f.password_field :password_confirmation, autocomplete: 'off', placeholder: 'パスワード (確認)', style: 'padding-left: 30px;'
        .uk-form-help-block#user-password-confirmation-error
    .uk-form-row
      = f.select :role, Grade::ROLE, {}, { class: 'uk-width-1-1' }

    .uk-modal-footer.uk-text-right
      .uk-button-group
        button.uk-button.uk-button-primary
          = fa_icon 'floppy-o', text: submit
        button.uk-button.uk-modal-close
          = fa_icon 'times', text: 'キャンセル'

app/views/admin/users/_list.html.slim
.uk-overflow-container
  table.uk-table.uk-table-striped
    thead
      tr
        th style="width: 150px;"
          = link_to new_admin_user_path, class: 'uk-button uk-button-mini uk-button-primary', remote: true do
            = fa_icon 'plus', text: '作成'
        th.bold style="width: 150px;" = sort_link(@search, :email, 'メールアドレス')
        th.bold style="width: 150px;" = sort_link(@search, :name, '名前')
        th.bold style="width: 100px;" = sort_link(@search, :age, '年齢')
        th.bold style="width: 50px;" = sort_link(@search, :sex, '性別')
        th.bold style="width: 50px;" = sort_link(@search, :role, '管理者')
        th.bold style="width: 100px;" = sort_link(@search, :physicals, '登録データ数')
        th.bold style="width: 150px;" = sort_link(@search, :last_sign_in_at, '最終ログイン時間')
    tbody
      - users.each do |user|
        - user = user.decorate
        tr
          td
            - unless user.access_locked?
              = link_to edit_admin_user_path(user.id), class: 'uk-button uk-button-mini uk-button-success uk-margin-small-right', remote: true
                = fa_icon 'pencil', text: '編集'
              = link_to lock_admin_user_path(user.id), class: 'uk-button uk-button-mini', method: :post, remote: true
                = fa_icon 'lock', text: '無効化'
            - else
              = link_to unlock_admin_user_path(user.id), class: 'uk-button uk-button-mini uk-button-primary uk-margin-small-right', method: :post, remote: true
                = fa_icon 'level-up', text: '有効化'
              = link_to admin_user_path(user.id), class: 'uk-button uk-button-mini uk-button-danger', method: :delete, remote: true
                = fa_icon 'trash', text: '削除'

          td #{user.email}
          td #{user.name}
          td #{user.age}
          td #{user.sex}
          td.uk-text-center = fa_icon 'check' if user.admin?
          td
            = link_to admin_user_path(user.id)
              = fa_icon 'files-o', text: "#{user.physicals.count} データ"
          td #{user.last_sign_in_at}
coffee:
  $('.select2').select2()

app/views/admin/users/index.html.slim
- @title = 'ユーザー'

h2.bold
  = fa_stacked_icon 'users inverse', base: 'square', text: @title

= search_form_for [:admin, @search], class: 'uk-form right' do |f|
  = fa_icon 'search', text: '名前から絞込'
  .uk-form-row
    = f.select :id_eq, User.all.map { |u| [u.name, u.id] }, {}, class: 'select2', style: 'width: 100px'
    button.uk-button.uk-button-primary onClick="$('.uk-panel > .uk-form').submit()"
      = fa_icon 'search', text: '検索'
hr
= render partial: 'admin/users/list', locals: { users: @users }
= paginate @users

coffee:
  $('#nav-admin').addClass('uk-active')

app/views/dashboards/index.html.slim
- @title = 'TOP'
.uk-block.uk-block-secondary.uk-contrast.uk-block-large
  .uk-container
    h1 みんなの健康を監視して平和な世界をつくろう
    .uk-grid.uk-grid-match data-uk-grid-margin=""
      .uk-width-medium-1-3 健康状態を登録して自身の健康をチェック
      .uk-width-medium-1-3 友人の健康状態を監視して友人の健康をチェック
      .uk-width-medium-1-3 グループを作ってみんなで監視しよう
      - unless user_signed_in?
        br
        .uk-width-medium-1-3
        .uk-width-medium-1-3 align="center" = link_to '登録', new_user_registration_path, class: 'uk-button-primary uk-button-large'

app/views/layouts/application.html.slim
doctype html
html
  head
    title #{@title} | weigery
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1"
    = stylesheet_link_tag    'application', 'data-turbolinks-track' => true, media: 'all'
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  body
    .loading-container = image_tag('loading.gif')
    .uk-modal

    nav.uk-navbar.uk-navbar-attached
      .uk-container.uk-container-center
        = link_to root_path, class: 'uk-navbar-brand'
          span.brand.bold weigery

        ul.uk-navbar-nav.uk-hidden-small
          - if user_signed_in?
            li
              = link_to user_physicals_path(current_user.id), data: { 'no-turbolink' => true }
                = fa_icon 'user-md', text: '自分の健康状態'

            - if current_user.admin?
              li
                = link_to admin_users_path
                  = fa_icon 'gears', text: '管理'

        .uk-navbar-flip.uk-hidden-small
          ul.uk-navbar-nav
            - if user_signed_in?
              li.uk-parent data-uk-dropdown=""
                a
                  = fa_icon 'user', text: current_user.name
                .uk-dropdown.uk-dropdown-navbar
                  ul.uk-nav.uk-nav-navbar
                    li
                      = link_to edit_user_registration_path
                        = fa_icon 'pencil fw', text: '編集'
                    li
                      = link_to destroy_user_session_path, method: :delete
                        = fa_icon 'sign-out fw', text: 'ログアウト'

            - else
              li
                = link_to new_user_session_path
                  = fa_icon 'sign-in', text: 'ログイン'

        .uk-navbar-flip.uk-visible-small
          a.uk-navbar-toggle href="#navbar-offcanvas" data-uk-offcanvas=""

    .uk-offcanvas#navbar-offcanvas
      .uk-offcanvas-bar.uk-offcanvas-bar-flip
        ul.uk-nav.uk-nav-offcanvas.uk-nav-parent-icon data-uk-nav=""
          li.uk-nav-header = fa_icon 'unlink', text: 'Link'
          - if user_signed_in?
            li.uk-nav-header = fa_icon 'database', text: 'マイページ'
            li
              = link_to user_physicals_path(current_user.id)
                = fa_icon 'heartbeat', text: '健康状態'
          - if user_signed_in? && current_user.admin?
            li.uk-nav-header = fa_icon 'gears', text: '管理'
            li = link_to '管理ページ', admin_users_path
          - if user_signed_in?
            li.uk-nav-header
              = fa_icon 'user fw', text: current_user.name
            li
              = link_to edit_user_registration_path(current_user.id)
                = fa_icon 'pencil fw', text: '設定'
            li
              = link_to destroy_user_session_path, method: :delete
                = fa_icon 'sign-out fw', text: 'ログアウト'
          - else
            li
              = link_to new_user_session_path
                = fa_icon 'sign-in fw', text: 'ログイン'

    .uk-container.uk-container-center.uk-margin-top.uk-margin-bottom
      = yield

    .uk-container.uk-container-center.uk-margin-bottom
      footer
        .relative
          .uk-panel.panel-default align="center"
            span &copy; weigery 2015
            - unless Rails.env.production?
              span style="float:right;" rev.#{Weigery::Application.config.git_revision}
- if notice
  javascript:
    UIkit.notify({ message: '#{notice}', timeout: 3000 });

- if alert
  javascript:
    UIkit.notify({ message: '#{alert}', timeout: 3000, status: 'danger' });

app/views/physicals/_form.html.slim
- unless physical
  - physical = current_user.physicals.new
  - physical.measurement_date = Date.today
  - title = '新規登録'
  - submit = '作成'
  - path = user_physicals_path(current_user.id)
- else
  - title = '編集'
  - submit = '更新'
  - path = user_physical_path(current_user.id, physical.id)

.uk-modal-dialog style="padding-bottom: 0"
  a.uk-modal-close.uk-close

  = form_for physical, url: path, html: { class: 'uk-form uk-form-horizontal' }, remote: true do |f|
    .uk-modal-header
      h4.bold
        = fa_icon 'heartbeat', text: title

    label.uk-form-label for="measurement_date"
      | 測定日
    .uk-form-controls
      = f.text_field :measurement_date, placeholder: Date.today, 'data-uk-datepicker' => "{format:'YYYY-MM-DD'}"
    label.uk-form-label for="height" 身長
    .uk-form-controls
      = f.text_field :height
    label.uk-form-label for="weight" 体重
    .uk-form-controls
      = f.text_field :weight
    label.uk-form-label for="sbp" 血圧(高)
    .uk-form-controls
      = f.text_field :sbp   , placeholder: '血圧(高)'
    label.uk-form-label for="dbp" 血圧(低)
    .uk-form-controls
      = f.text_field :dbp   , placeholder: '血圧(低)'
    label.uk-form-label for="pulse" 脈拍
    .uk-form-controls
      = f.text_field :pulse , placeholder: '脈拍'

    .uk-modal-footer.uk-text-right
      .uk-button-group
        button.uk-button.uk-button-primary
          = fa_icon 'floppy-o', text: submit
        button.uk-button.uk-modal-close
          = fa_icon 'times', text: 'キャンセル'

app/views/physicals/_graph.html.slim
= high_chart("height_weight", @height_weight)

= high_chart("bp_pulse", @bp_pulse)

app/views/physicals/_management.html.slim
br
= link_to new_user_physical_path, remote: :true, class: 'uk-button uk-button-success'
  = fa_icon 'plus', text: '新規作成'
table.uk-table
  thead
    tr
      - if user_signed_in? && current_user == @user
        th.bold style="width: 18%;" メニュー
      th.bold style="width: 50px;" id
      th.bold style="width: 100px;" 測定日
      th.bold style="width: 50px;" 身長
      th.bold style="width: 50px;" 体重
      th.bold style="width: 80px;" 血圧(高)
      th.bold style="width: 80px;" 血圧(低)
      th.bold style="width: 50px;" 脈拍
      th.bold style="width: 50px;" BMI

  tbody
    - @user.physicals.each do |physical|
      - physical = physical.decorate
      tr
        - if user_signed_in? && current_user == @user
          td.physicals-menu
            = link_to edit_user_physical_path(user_id: physical.user_id, id: physical.id), remote: true, class: 'uk-button uk-button-mini uk-button-primary uk-margin-samll-right'
              = fa_icon 'pencil', text: '編集'
            = link_to  user_physical_path(physical.user_id, physical.id), remote: true, method: :delete, class: 'uk-button uk-button-mini uk-button-danger uk-margin-samll-right'
              = fa_icon 'trash', text: '削除'
        td = physical.id
        td = physical.measurement_date
        td = physical.height
        td = physical.weight
        td = physical.sbp
        td = physical.dbp
        td = physical.pulse
        td = physical.bmi

app/views/physicals/index.html.slim
ul.uk-tab data-uk-tab="{connect:'#tab-content'}"
  li.uk-active
    a href="" 管理
  li
    a href="" グラフ

ul#tab-content.uk-switcher
  li.uk-active
    = render partial: 'management'
  li
    = render partial: 'graph'